apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: pepgmp-prod
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: pepgmp-backend:latest
        # 实际生产中应使用特定标签，例如：pepgmp-backend:20251215
        # 从私有仓库拉取镜像可能需要配置imagePullSecrets
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pepgmp-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pepgmp-secrets
              key: REDIS_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pepgmp-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pepgmp-secrets
              key: JWT_SECRET_KEY
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pepgmp-secrets
              key: ADMIN_PASSWORD
        # 其他环境变量从ConfigMap注入
        envFrom:
        - configMapRef:
            name: pepgmp-config
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "6Gi"
            cpu: "3"
          limits:
            memory: "10Gi"
            cpu: "6"
            nvidia.com/gpu: 1  # 需要GPU节点
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: models-volume
          mountPath: /app/models
          readOnly: true
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: output-volume
          mountPath: /app/output
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      volumes:
      - name: config-volume
        configMap:
          name: pepgmp-config
          items:
          - key: CAMERAS_YAML_PATH
            path: cameras.yaml
          # 可添加其他配置文件
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: pepgmp-prod
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP