"""Add core business tables to SQLAlchemy models

Revision ID: de374ef6dace
Revises:
Create Date: 2025-12-22 13:10:14.210662

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "de374ef6dace"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_stats_camera_hour"), table_name="statistics_hourly")
    op.drop_index(op.f("idx_stats_hour"), table_name="statistics_hourly")
    op.drop_table("statistics_hourly")
    op.drop_index(op.f("idx_behaviors_detection_id"), table_name="behaviors")
    op.drop_index(op.f("idx_behaviors_type"), table_name="behaviors")
    op.drop_table("behaviors")
    op.drop_index(op.f("idx_zones_camera_id"), table_name="detection_zones")
    op.drop_table("detection_zones")
    op.drop_index(op.f("idx_statistics_camera_date"), table_name="statistics")
    op.drop_table("statistics")
    op.drop_table("users")
    op.drop_index(op.f("idx_detections_camera_id"), table_name="detections")
    op.drop_index(op.f("idx_detections_detected_at"), table_name="detections")
    op.drop_index(op.f("idx_detections_type"), table_name="detections")
    op.drop_table("detections")
    op.drop_table("system_configs")
    op.drop_index(op.f("idx_alerts_camera_id"), table_name="alerts")
    op.drop_index(op.f("idx_alerts_created_at"), table_name="alerts")
    op.drop_index(op.f("idx_alerts_status"), table_name="alerts")
    op.drop_table("alerts")
    op.alter_column(
        "alert_history",
        "rule_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_history", "camera_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column("alert_history", "message", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "alert_history",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_history",
        "notification_channels_used",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_alert_history_camera"), table_name="alert_history")
    op.drop_index(op.f("idx_alert_history_rule"), table_name="alert_history")
    op.drop_index(op.f("idx_alert_history_timestamp"), table_name="alert_history")
    op.create_index(
        op.f("ix_alert_history_alert_type"),
        "alert_history",
        ["alert_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_history_camera_id"), "alert_history", ["camera_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_history_timestamp"), "alert_history", ["timestamp"], unique=False
    )
    op.drop_constraint(
        op.f("alert_history_rule_id_fkey"), "alert_history", type_="foreignkey"
    )
    op.drop_table_comment(
        "alert_history", existing_comment="告警历史表 - 记录所有触发的告警", schema=None
    )
    op.drop_column("alert_history", "created_at")
    op.add_column(
        "alert_rules", sa.Column("alert_type", sa.String(length=50), nullable=False)
    )
    op.add_column("alert_rules", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column(
        "alert_rules",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "alert_rules",
        "conditions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_rules",
        "notification_channels",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_alert_camera"),
        table_name="alert_rules",
        postgresql_where="(enabled = true)",
    )
    op.drop_index(op.f("idx_alert_enabled"), table_name="alert_rules")
    op.drop_index(
        op.f("idx_alert_type"),
        table_name="alert_rules",
        postgresql_where="(enabled = true)",
    )
    op.create_index(
        op.f("ix_alert_rules_alert_type"), "alert_rules", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_alert_rules_is_active"), "alert_rules", ["is_active"], unique=False
    )
    op.drop_table_comment(
        "alert_rules", existing_comment="告警规则表 - 定义各种告警条件", schema=None
    )
    op.drop_column("alert_rules", "rule_type")
    op.drop_column("alert_rules", "enabled")
    op.drop_column("alert_rules", "created_by")
    op.drop_column("alert_rules", "camera_id")
    op.drop_column("alert_rules", "priority")
    op.drop_column("alert_rules", "recipients")
    op.alter_column(
        "cameras",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.alter_column(
        "cameras",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "cameras",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "cameras",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "detection_records",
        "camera_id",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="摄像头ID",
        existing_nullable=False,
    )
    op.alter_column(
        "detection_records",
        "frame_number",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="帧编号",
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "person_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="检测到的人数",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "detection_records",
        "hairnet_violations",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="未佩戴发网的人数",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "detection_records",
        "person_detections",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "hairnet_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "handwash_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "sanitize_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "processing_time",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="处理耗时(秒)",
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "objects",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_detection_camera_id"), table_name="detection_records")
    op.drop_index(
        op.f("idx_detection_camera_timestamp"), table_name="detection_records"
    )
    op.drop_index(
        op.f("idx_detection_records_camera_id"), table_name="detection_records"
    )
    op.drop_index(
        op.f("idx_detection_records_confidence"), table_name="detection_records"
    )
    op.drop_index(
        op.f("idx_detection_records_timestamp"), table_name="detection_records"
    )
    op.drop_index(op.f("idx_detection_timestamp"), table_name="detection_records")
    op.create_index(
        op.f("ix_detection_records_camera_id"),
        "detection_records",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detection_records_timestamp"),
        "detection_records",
        ["timestamp"],
        unique=False,
    )
    op.drop_table_comment(
        "detection_records", existing_comment="检测记录表 - 存储每次检测的详细结果", schema=None
    )
    op.alter_column(
        "regions",
        "polygon",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "regions",
        "rules",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "regions",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "regions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "regions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("idx_regions_active"), table_name="regions")
    op.drop_index(
        op.f("idx_regions_camera_id"),
        table_name="regions",
        postgresql_where="(camera_id IS NOT NULL)",
    )
    op.drop_index(op.f("idx_regions_type"), table_name="regions")
    op.alter_column(
        "violation_events",
        "violation_type",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="违规类型: no_hairnet(未戴发网), no_handwash(未洗手), no_sanitize(未消毒)",
        existing_nullable=False,
    )
    op.alter_column(
        "violation_events",
        "bbox",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "violation_events",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="处理状态: pending(待处理), confirmed(已确认), false_positive(误报), resolved(已解决)",
        existing_nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_index(op.f("idx_violation_camera_status"), table_name="violation_events")
    op.drop_index(op.f("idx_violation_camera_timestamp"), table_name="violation_events")
    op.drop_index(op.f("idx_violation_status"), table_name="violation_events")
    op.drop_index(op.f("idx_violation_type"), table_name="violation_events")
    op.create_index(
        op.f("ix_violation_events_camera_id"),
        "violation_events",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_status"), "violation_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_violation_events_timestamp"),
        "violation_events",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violation_events_violation_type"),
        "violation_events",
        ["violation_type"],
        unique=False,
    )
    op.drop_constraint(
        op.f("violation_events_detection_id_fkey"),
        "violation_events",
        type_="foreignkey",
    )
    op.drop_table_comment(
        "violation_events", existing_comment="违规事件表 - 记录所有违规行为", schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "violation_events", "违规事件表 - 记录所有违规行为", existing_comment=None, schema=None
    )
    op.create_foreign_key(
        op.f("violation_events_detection_id_fkey"),
        "violation_events",
        "detection_records",
        ["detection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_violation_events_violation_type"), table_name="violation_events"
    )
    op.drop_index(op.f("ix_violation_events_timestamp"), table_name="violation_events")
    op.drop_index(op.f("ix_violation_events_status"), table_name="violation_events")
    op.drop_index(op.f("ix_violation_events_camera_id"), table_name="violation_events")
    op.create_index(
        op.f("idx_violation_type"), "violation_events", ["violation_type"], unique=False
    )
    op.create_index(
        op.f("idx_violation_status"), "violation_events", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_violation_camera_timestamp"),
        "violation_events",
        ["camera_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_violation_camera_status"),
        "violation_events",
        ["camera_id", "status"],
        unique=False,
    )
    op.alter_column(
        "violation_events",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="处理状态: pending(待处理), confirmed(已确认), false_positive(误报), resolved(已解决)",
        existing_nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "violation_events",
        "bbox",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "violation_events",
        "violation_type",
        existing_type=sa.VARCHAR(length=50),
        comment="违规类型: no_hairnet(未戴发网), no_handwash(未洗手), no_sanitize(未消毒)",
        existing_nullable=False,
    )
    op.create_index(op.f("idx_regions_type"), "regions", ["region_type"], unique=False)
    op.create_index(
        op.f("idx_regions_camera_id"),
        "regions",
        ["camera_id"],
        unique=False,
        postgresql_where="(camera_id IS NOT NULL)",
    )
    op.create_index(op.f("idx_regions_active"), "regions", ["is_active"], unique=False)
    op.alter_column(
        "regions",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "regions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "regions",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "regions",
        "rules",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "regions",
        "polygon",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_table_comment(
        "detection_records", "检测记录表 - 存储每次检测的详细结果", existing_comment=None, schema=None
    )
    op.drop_index(
        op.f("ix_detection_records_timestamp"), table_name="detection_records"
    )
    op.drop_index(
        op.f("ix_detection_records_camera_id"), table_name="detection_records"
    )
    op.create_index(
        op.f("idx_detection_timestamp"),
        "detection_records",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_detection_records_timestamp"),
        "detection_records",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("idx_detection_records_confidence"),
        "detection_records",
        ["confidence"],
        unique=False,
    )
    op.create_index(
        op.f("idx_detection_records_camera_id"),
        "detection_records",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_detection_camera_timestamp"),
        "detection_records",
        ["camera_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_detection_camera_id"),
        "detection_records",
        ["camera_id"],
        unique=False,
    )
    op.alter_column(
        "detection_records",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "objects",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "processing_time",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="处理耗时(秒)",
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "sanitize_results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "handwash_results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "hairnet_results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "person_detections",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "hairnet_violations",
        existing_type=sa.INTEGER(),
        comment="未佩戴发网的人数",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "detection_records",
        "person_count",
        existing_type=sa.INTEGER(),
        comment="检测到的人数",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "detection_records",
        "frame_number",
        existing_type=sa.INTEGER(),
        comment="帧编号",
        existing_nullable=True,
    )
    op.alter_column(
        "detection_records",
        "camera_id",
        existing_type=sa.VARCHAR(length=50),
        comment="摄像头ID",
        existing_nullable=False,
    )
    op.alter_column(
        "cameras",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "cameras",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "cameras",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "cameras",
        "config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "cameras",
        "id",
        existing_type=sa.String(length=50),
        type_=sa.UUID(),
        existing_nullable=False,
        existing_server_default=sa.text("uuid_generate_v4()"),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "priority",
            sa.VARCHAR(length=20),
            server_default=sa.text("'medium'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "camera_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "created_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "alert_rules",
        sa.Column(
            "rule_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="规则类型: violation_threshold(违规阈值), continuous_violation(持续违规), no_detection(无检测)",
        ),
    )
    op.create_table_comment(
        "alert_rules", "告警规则表 - 定义各种告警条件", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_alert_rules_is_active"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_alert_type"), table_name="alert_rules")
    op.create_index(
        op.f("idx_alert_type"),
        "alert_rules",
        ["rule_type"],
        unique=False,
        postgresql_where="(enabled = true)",
    )
    op.create_index(op.f("idx_alert_enabled"), "alert_rules", ["enabled"], unique=False)
    op.create_index(
        op.f("idx_alert_camera"),
        "alert_rules",
        ["camera_id"],
        unique=False,
        postgresql_where="(enabled = true)",
    )
    op.alter_column(
        "alert_rules",
        "notification_channels",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_rules",
        "conditions",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "alert_rules",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("alert_rules", "is_active")
    op.drop_column("alert_rules", "alert_type")
    op.add_column(
        "alert_history",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table_comment(
        "alert_history", "告警历史表 - 记录所有触发的告警", existing_comment=None, schema=None
    )
    op.create_foreign_key(
        op.f("alert_history_rule_id_fkey"),
        "alert_history",
        "alert_rules",
        ["rule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_alert_history_timestamp"), table_name="alert_history")
    op.drop_index(op.f("ix_alert_history_camera_id"), table_name="alert_history")
    op.drop_index(op.f("ix_alert_history_alert_type"), table_name="alert_history")
    op.create_index(
        op.f("idx_alert_history_timestamp"),
        "alert_history",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_alert_history_rule"),
        "alert_history",
        ["rule_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_alert_history_camera"),
        "alert_history",
        ["camera_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.alter_column(
        "alert_history",
        "notification_channels_used",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "alert_history",
        "details",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column("alert_history", "message", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "alert_history",
        "camera_id",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "alert_history",
        "rule_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.create_table(
        "alerts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("zone_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("detection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "alert_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "severity",
            sa.VARCHAR(length=20),
            server_default=sa.text("'medium'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("acknowledged_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "acknowledged_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("alerts_acknowledged_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("alerts_camera_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name=op.f("alerts_detection_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["detection_zones.id"],
            name=op.f("alerts_zone_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("alerts_pkey")),
    )
    op.create_index(op.f("idx_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(
        op.f("idx_alerts_created_at"), "alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("idx_alerts_camera_id"), "alerts", ["camera_id"], unique=False)
    op.create_table(
        "system_configs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "config_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config_value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("system_configs_pkey")),
        sa.UniqueConstraint(
            "config_key",
            name=op.f("system_configs_config_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "detections",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("zone_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "detection_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "bbox",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "image_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "detected_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "processed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name="detections_camera_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["detection_zones.id"],
            name="detections_zone_id_fkey",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="detections_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("idx_detections_type"), "detections", ["detection_type"], unique=False
    )
    op.create_index(
        op.f("idx_detections_detected_at"), "detections", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("idx_detections_camera_id"), "detections", ["camera_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            server_default=sa.text("'user'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("users_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name=op.f("users_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "statistics",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("zone_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "stat_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("stat_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("stat_hour", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("statistics_camera_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["detection_zones.id"],
            name=op.f("statistics_zone_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("statistics_pkey")),
    )
    op.create_index(
        op.f("idx_statistics_camera_date"),
        "statistics",
        ["camera_id", "stat_date"],
        unique=False,
    )
    op.create_table(
        "detection_zones",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "polygon",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "zone_type",
            sa.VARCHAR(length=50),
            server_default=sa.text("'general'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rules",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name="detection_zones_camera_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="detection_zones_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("idx_zones_camera_id"), "detection_zones", ["camera_id"], unique=False
    )
    op.create_table(
        "behaviors",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("detection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "behavior_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "detected_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["detection_id"],
            ["detections.id"],
            name=op.f("behaviors_detection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("behaviors_pkey")),
    )
    op.create_index(
        op.f("idx_behaviors_type"), "behaviors", ["behavior_type"], unique=False
    )
    op.create_index(
        op.f("idx_behaviors_detection_id"), "behaviors", ["detection_id"], unique=False
    )
    op.create_table(
        "statistics_hourly",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "camera_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "hour_start",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="小时开始时间 (例: 2025-10-14 14:00:00)",
        ),
        sa.Column(
            "total_frames",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_persons",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_hairnet_violations",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_handwash_events",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_sanitize_events",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_fps",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_processing_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "min_processing_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_processing_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("statistics_hourly_pkey")),
        sa.UniqueConstraint(
            "camera_id",
            "hour_start",
            name=op.f("uq_camera_hour"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="小时统计表 - 按小时汇总检测数据",
    )
    op.create_index(
        op.f("idx_stats_hour"),
        "statistics_hourly",
        [sa.literal_column("hour_start DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_stats_camera_hour"),
        "statistics_hourly",
        ["camera_id", sa.literal_column("hour_start DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
